# Generated by Django 4.2.7 on 2023-12-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunanabu', models.CharField(max_length=100)),
                ('bayaninAbu', models.TextField()),
                ('fasaha', models.CharField(max_length=20)),
            ],
        ),
    ]
