# Generated by Django 4.2.7 on 2023-12-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='bayaninAbu',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='fasaha',
            new_name='technology',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='sunanabu',
            new_name='title',
        ),
    ]
